namespace AuctionService.Application.DTOs;

/// <summary>
/// Represents a single image in an auction's gallery.
/// <para>
/// <c>SortOrder = 0</c> is the primary image used by listings, search results, and link previews.
/// All other images are shown on the auction detail page only.
/// <c>ThumbnailUrl</c> is optional — when absent, the full <c>Url</c> is used as the fallback.
/// </para>
/// </summary>
public class ImageDto
{
    /// <summary>The full-size image URL (platform-hosted or externally hosted).</summary>
    public required string Url { get; init; }

    /// <summary>
    /// The WebP thumbnail URL (max 400px wide), generated by <c>POST api/auctions/thumbnail</c>.
    /// Null when no thumbnail has been generated yet.
    /// </summary>
    public string? ThumbnailUrl { get; init; }

    /// <summary>
    /// Display order within the gallery. <c>0</c> identifies the primary image.
    /// </summary>
    public int SortOrder { get; init; }
}
