import path from "node:path";

/**
 * `e2e/.auth/` -- gitignored (see `.gitignore`'s "playwright" section), regenerated by
 * `../global-setup.ts` at the start of every run. Holds one Playwright `storageState` JSON
 * file per seeded user this suite signs in as (today: bob/alice/tom -- see `./test-data.ts`'s
 * `SEEDED_USERS`), each containing that user's real next-auth session cookie captured right
 * after a genuine `signInViaIdentityServer` round-trip.
 *
 * Computed from THIS file's own `__dirname` (not the caller's) so `storageStatePath` resolves
 * identically regardless of which spec/setup script imports it -- `fixtures/` is always exactly
 * one level below `e2e/`.
 */
export const AUTH_DIR = path.join(__dirname, "..", ".auth");

/**
 * Path `global-setup.ts` writes a given seeded user's `storageState` to, and specs/helpers read
 * it back from -- via `test.use({ storageState: storageStatePath("bob") })` for a whole spec
 * file, or `browser.newContext({ storageState: storageStatePath("alice") })` for one signed-in
 * context alongside others in the same test (Task 15 Batch C's multi-context bidding/real-time
 * specs).
 */
export function storageStatePath(username: string): string {
  return path.join(AUTH_DIR, `${username}.json`);
}
